### ISSUE TITLE
Interested in adding winrm support

### ISSUE THREAD

**Issue by chrisevett** [cashman04/lita-ssh-run#3]
I'm interested in extending this plugin to add winrm support for windows machines. I'm thinking that when you first get the 'lita run' command you would prompt for a OS type in addition to the username and password. If the os type is windows we would then invoke the command using this library: https://github.com/WinRb/WinRM .

Are you guys on board with that? It makes sense to me to keep it in the same plugin for simplicity

**Comment by cashman04** [comment]
Ya, that is fine with me.  I haven't done much on this since I wrote it just to play with lita plugins, so I'm completely open to any improvements if it is usable for you.

**Comment by chrisevett** [comment]
Cool, I've opened a pull request. I already have people using this in our chat and they all love it.

**Comment by cashman04** [comment]
Merged. I'll build and push this version of the gem in a few minutes and reply when done.

**Comment by chrisevett** [comment]
Opened another PR to fix readme formatting. Also as a friendly reminder can we get this pushed to rubygems when you get a chance?

**Comment by cashman04** [comment]
Done and done.  Sorry, I completely forgot to build/push it the other day.  It is out there now. Let me know if there are any issues.

**Comment by chrisevett** [comment]
Great. Thanks for your help.
